name: Release Development Polkadot Operator to Charmhub

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Polkadot charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v32.0.0
    with:
      charmcraft-snap-revision: 6672
      cache: false

  release:
    name: Release charm to latest/edge/develop channel
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v32.0.0
    with:
      track: latest/edge/develop
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create GitHub release
